# mise で管理するツールのグローバル バージョンを指定する。
# ~/.config/mise/config.toml として使用されるもの。
# https://mise.jdx.dev/configuration.html#global-config-config-mise-config-toml
[tools]
aws-cli = "2.37.8"
go = "1.27.1"
node = "26.10.0"
poetry = { version = "2.5.1", depends = "python" }
python = "3.14.7"
ruby = "4.0.7"
terraform = "1.16.4"
tfsec = "1.28.14"
