# mise で管理するツールのグローバル バージョンを指定する。
# ~/.config/mise/config.toml として使用されるもの。
# https://mise.jdx.dev/configuration.html#global-config-config-mise-config-toml
[tools]
awscli = "2.27.4"
go = "1.24.2"
node = "22.14.0"
poetry = "1.7.1"
python = "3.13.3"
ruby = "3.4.2"
terraform = "1.12.2"
tfsec = "1.28.13"
