# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more
# https://github.com/rossmacarthur/sheldon#readme
#
shell = "zsh"

# zsh-defer と Sheldon のテンプレート機能を組み合わせることでプラグイン遅延読込みを実現する。
# https://zenn.dev/ganta/articles/e1e0746136ce67#%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E3%81%AE%E9%81%85%E5%BB%B6%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%81%BF
#
# 1. ここでは、デフォルト設定として遅延読込を設定する。
# シェル起動時にプラグインを読み込ませる場合は、プラグイン毎に apply = ["source"] を設定する。
apply = ["defer"]
# 2. プラグイン遅延読込み用のテンプレートを定義する。
# apply = ["defer"] を設定することで、そのプラグインが遅延読み込みされる。
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
fpath = 'fpath=("{{ dir }}" $fpath)'

# -----------------------------------------------------------
# プラグインは、ここで記載の順に source される。記載順に注意すること！
# -----------------------------------------------------------

# プラグインの遅延読込機能を提供する。
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]           # zsh 起動時に読み込まれる。

# 作業ディレクトリの .env から環境変数をロードする。
[plugins.env-zsh]
github = "johnhamelink/env-zsh"
apply = ["source"]

# プロンプトで色を使用出来るようにする。
[plugins.colors]
inline = "autoload -Uz colors && zsh-defer colors"

# シンタックスハイライト
[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

# コマンド入力時にグレーアウトした文字列で入力候補を表示する。
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

# mise をシェルで有効化する
# https://mise.jdx.dev/getting-started.html#activate-mise
[plugins.mise-activate]
inline = 'eval "$(mise activate zsh)"'

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# zsh 補完機能を有効にする。
# 下記 2つは、aws-cli の入力補完を有効化するためのもの。
# - `autoload bashcompinit && bashcompinit`
# - `complete -C '/usr/local/bin/aws_completer' aws`
[plugins.compinit]
inline = "autoload bashcompinit && bashcompinit && autoload -Uz compinit && zsh-defer compinit && zsh-defer complete -C '/usr/local/bin/aws_completer' aws"

# Ctrl-R で、コマンド履歴を複数キーワードの AND で検索する。
[plugins.history-search]
github = "z-shell/H-S-MW"

# zsh 起動時に同時に読み込むべき設定を sync.zsh へ書く。
# 現在は、 .zshrc 内へ書くことで問題ないため、この設定はコメントアウトする。
# [plugins.dotfile-sync]
# local = "~/dotfiles/zsh"
# use   = ["sync.zsh"]
# apply = ["source"]

[plugins.dotfile-defers]
local = "~/dotfiles/zsh"
use = ["{!sync,*}.zsh"]
